### ISSUE TITLE
uninitialized constant ActionMailer::DeliveryJob with latest rails/master

### ISSUE THREAD

**Issue by mhenrixon** [rspec/rspec-rails#2531]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: 3.0.2
Rails version: 7.0.0 @ a0e14a8bfebf5f4bd4b66d1d468c844ab3e9d704
RSpec version: 5.0.2

## Observed behaviour

```ruby
6) Pitches::AcceptRequest#call updates pitch status
     Failure/Error:
       expect { call }.to change { User.count }.by(1)
         .and change { BuyerProfile.count }.by(1)
         .and change { pitch.reload.buyer_profile }.from(nil)
         .and change { prospect.reload.invitation_accepted_at }.from(nil)
         .and have_enqueued_email(PitchMailer, :request_accepted)

     NameError:
       uninitialized constant ActionMailer::DeliveryJob
       Did you mean?  ActionMailer::MailDeliveryJob
     # ./spec/services/pitches/accept_request_spec.rb:36:in `block (3 levels) in <main>'
     # -e:1:in `<main>'
```

## Expected behaviour

Test was working before upgrading rails version

## Can you provide an example app?

https://github.com/mhenrixon/rspec-rails-issue-2531 shows the error nicely

**Comment by mhenrixon** [comment]
Already fixed in https://github.com/rspec/rspec-rails/pull/2516

**Comment by mhenrixon** [comment]
If I define the missing const

```ruby
unless ActionMailer.const_defined?("DeliveryJob")
  ActionMailer.const_set(:DeliveryJob, ActionMailer::MailDeliveryJob)
end
```

I get other errors:

```ruby
 4) Pitches::AcceptPitch#call when buyer has not connected with stripe updates pitch status
     Failure/Error:
       expect { call }.to change { pitch.reload.state }.to("buyer_accepted")
         .and have_enqueued_email(PitchMailer, :request_accepted)

     NameError:
       uninitialized constant ActionMailer::Parameterized::DeliveryJob
       Did you mean?  ActionMailer::DeliveryJob
```

So it does seem like something has changed and rspec-rails needs to be tweaked.

**Comment by pirj** [comment]
What if you replace (in https://github.com/rspec/rspec-rails/blob/d3e7b85877fcbcec63f8a76434d8750e7f3b7aef/lib/rspec/rails/matchers/have_enqueued_mail.rb#L134):
```diff
-           job[:job] <= ActionMailer::DeliveryJob
+           defined?(ActionMailer::DeliveryJob) && job[:job] <= ActionMailer::DeliveryJob
```
will it fix your error?

**Comment by mhenrixon** [comment]
@pirj then I get the other error I posted:

```ruby
Failures:

  1) Article sends emails about published articles
     Failure/Error:
       expect { Article.create!(title: "Some title", slug: "some-title") }
         .to have_enqueued_email(ArticleMailer, :article_published)

     NameError:
       uninitialized constant ActionMailer::Parameterized::DeliveryJob
       Did you mean?  ActionMailer::MailDeliveryJob
     # ./spec/models/article_spec.rb:7:in `block (2 levels) in <main>'
```

**Comment by mhenrixon** [comment]
This seems to be the commit! https://github.com/rails/rails/commit/ddc7fb6e6ee957aae35f1bb11d35c2d3e3b0cdda

**Comment by mhenrixon** [comment]
If I change: 

```ruby
# FROM
def parameterized_mail?(job)
  RSpec::Rails::FeatureCheck.has_action_mailer_parameterized? && job[:job] <= ActionMailer::Parameterized::DeliveryJob
end

# TO
def parameterized_mail?(job)
   RSpec::Rails::FeatureCheck.has_action_mailer_parameterized? && job[:job] <= ActionMailer::MailDeliveryJob
end
```

At least the error goes away.

**Comment by mhenrixon** [comment]
Added this in `spec/support` and it seems to work

```ruby
# This patches rspec-rails to support rails 7.0
module RSpec
  module Rails
    module Matchers
      class HaveEnqueuedMail
        def legacy_mail?(job)
          defined?(ActionMailer::DeliveryJob) && job[:job] <= ActionMailer::DeliveryJob
        end

        def parameterized_mail?(job)
          RSpec::Rails::FeatureCheck.has_action_mailer_parameterized? && job[:job] <= ActionMailer::MailDeliveryJob
        end

        def unified_mail?(job)
          RSpec::Rails::FeatureCheck.has_action_mailer_unified_delivery? && job[:job] <= ActionMailer::MailDeliveryJob
        end
      end
    end
  end
end
```

**Comment by pirj** [comment]
Would you open a PR with a proper fix that would work with 5.2, 6.0, 6.1 and most recent 7.0?

**Comment by pirj** [comment]
You won't even have to write new specs for this code. Rails edge build already fails:

```
NameError:
  uninitialized constant ActionMailer::DeliveryJob
# ./spec/rspec/rails/matchers/have_enqueued_mail_spec.rb:25:in `<top (required)>'
```

**Comment by mhenrixon** [comment]
Perfect, I'll sort out a PR then! Thanks for following up

**Comment by mhenrixon** [comment]
Added PR @pirj, please let me know if there is anything I should improve to get it merged.

**Comment by pirj** [comment]
It seems that specs were failing due to broken argument matching. It was mostly fixed in #2516, and with an additional small fix and this PR it all passes specs. A combo frankenrequest is #2546.

**Comment by mhenrixon** [comment]
Thanks @pirj feel free to close this one if #2546 fixes the issue! I am still swamped with my attempt to make our new home livable. Just catching up on some notifications.

**Comment by dwightwatson** [comment]
Any chance of getting this in a tagged release soon?

**Comment by Petercopter** [comment]
I'm still getting the same error with `rspec-rails 5.1.1` and `rails 7.0.2.3`

**Comment by pirj** [comment]
@Petercopter [The fix](https://github.com/rspec/rspec-rails/blob/4ded7a46bbc8e5a06d4bdfcd3914f50eeb15ac22/lib/rspec/rails/matchers/have_enqueued_mail.rb#L169) is in `main`, but [not in 5.1.1](https://github.com/rspec/rspec-rails/blob/v5.1.1/lib/rspec/rails/matchers/have_enqueued_mail.rb#L161). I suggest using `main` until the fix is released on RubyGems.

**Comment by rickychilcott** [comment]
The problem with `main` is that it's version is 6.0.0-pre and other rspec libs don't yet support `6.x`. Will this only be available in a `6.x` release?

**Comment by pirj** [comment]
>  other rspec libs (external) don't yet support 6.x

Other RSpec libs do not depend on `rspec-rails`. Do you mean that [`rspec-rails`'s `main` branch depends on pre-release versions of other RSpec libs](https://github.com/rspec/rspec-rails/blob/3818055b95a09b7fc88c7e8884f9bc6ace781218/rspec-rails.gemspec#L51)? Yes, this is true. You'll have to specify to use them from GitHub source, too.

> Will this only be available in a 6.x release?

Yes, as this is a Rails 7 specific fix, and the version to support Rails 7 is RSpec Rails 6.

**Comment by JonRowe** [comment]
This has been released as `6.0.0.rc1` theres still potential for the breaking change to the mailer api to do with params / args matching, but those needing support from a tagged release can now get this via rc1.

Rails 7 support is only via version 6.x per our versioning strategy.
